.TH "ESLINT\-MD" "1" "February 2015" "" ""
.SH "NAME"
\fBeslint-md\fR \- Lint JavaScript in markdown code\-blocks
.SH SYNOPSIS
.P
\fBeslint\-md\fR [options] file\.md [file\.md] [dir]
.SH DESCRIPTION
.P
\fBeslint\-md\fR lints JavaScript in markdown code\-blocks with ESLint\.
.P
Logs verbose debugging information when \fB$DEBUG\fR is set to \fB"eslint:*"\fR\|\.
.P
Options are as follows:
.RS 0
.IP \(bu 2
\fB\-h\fR, \fB\-\-help\fR: Show help;
.IP \(bu 2
\fB\-c\fR, \fB\-\-config\fR \fIpath::String\fR: Use configuration from this file;
.IP \(bu 2
\fB\-\-rulesdir\fR [\fIpath::String\fR]: Use additional rules from this directory;
.IP \(bu 2
\fB\-f\fR, \fB\-\-format\fR \fIString\fR: Use a specific output format \- default: stylish;
.IP \(bu 2
\fB\-v\fR, \fB\-\-version\fR: Outputs the version number;
.IP \(bu 2
\fB\-\-reset\fR: Set all default rules to off \- default: false;
.IP \(bu 2
\fB\-\-no\-eslintrc\fR: Disable use of configuration from \.eslintrc;
.IP \(bu 2
\fB\-\-env\fR [\fIString\fR]: Specify environments;
.IP \(bu 2
\fB\-\-ext\fR [\fIString\fR]: Specify Markdown file extensions \- default: \.md, \.markd, \.markdown;
.IP \(bu 2
\fB\-\-plugin\fR [\fIString\fR]: Specify plugins;
.IP \(bu 2
\fB\-\-global\fR [\fIString\fR]: Define global variables;
.IP \(bu 2
\fB\-\-rule\fR \fIObject\fR: Specify rules;
.IP \(bu 2
\fB\-\-ignore\-path\fR \fIpath::String\fR: Specify path of ignore file;
.IP \(bu 2
\fB\-\-no\-ignore\fR: Disable use of \.eslintignore;
.IP \(bu 2
\fB\-\-no\-color\fR: Disable color in piped output;
.IP \(bu 2
\fB\-o\fR, \fB\-\-output\-file\fR \fIpath::String\fR: Specify file to write report to;
.IP \(bu 2
\fB\-\-quiet\fR: Report errors only \- default: false;
.IP \(bu 2
\fB\-\-stdin\fR: Lint code provided on <STDIN> \- default: false\.

.RE
.SH BUGS
.P
<https://github\.com/wooorm/eslint\-md/issues>
.SH AUTHOR
.P
Written by Titus Wormer <tituswormer@gmail\.com>

